### PR TITLE
add runtimePlatform to CONDITIONAL_OPTIONS

### PR DESCRIPTION
**Pull request by tsgoff**
ecs-deploy is overwriting runtimePlatform containing operatingSystemFamily and cpuArchitecture

### CODE REVIEW

**Comment by zhemaituk** [comment]
@forevermatt could you please review?

**Review by forevermatt — APPROVED** [review]

**Review by Baggerone — APPROVED** [review]

**Comment by zhemaituk** [comment]
@forevermatt @Baggerone thank you for the review! Can you merge it please?

**Comment by forevermatt** [comment]
> @forevermatt @Baggerone thank you for the review! Can you merge it please?

@zhemaituk Thanks for the reminder. I've merged it into develop, and I've also now bumped the "roll a release" task up higher on our priority list, so it should get attention sooner (hopefully either this week or next). Sorry for the delay, and thanks again for your help with this fix. 👍

**Comment by forevermatt** [comment]
As a side note, we haven't quite finished updating our Homebrew tap to point to this new release, though, so if you're using Homebrew to install ecs-deploy it may be another day or two before that's available to you.

**Comment by zhemaituk** [comment]
Thank you, the latest version works like a charm.
I guess official docker images are not released anymore, I built one myself, but wonder if I were looking in a wrong place.

**Comment by forevermatt** [comment]
> I guess official docker images are not released anymore, I built one myself, but wonder if I were looking in a wrong place.

We just recently discovered that our docker image build process for this was no longer working. (When Docker Hub stopped building images for free, this one fell through the cracks, so to speak.) We have it in our backlog now to fix that, but I'm glad you were able to simply build it yourself in the meantime.

**Pull request merged**
