### PR TITLE
Support multi level images

### PR DESCRIPTION
**Pull request by inakiabt**
Like: registry.example.com/repo/image/name:0.1.1

### CODE REVIEW

**Comment by fillup** [comment]
Hi @inakiabt I just tested this little change in the new code base that has unit tests and it breaks several tests related to parsing the image name. I see you're updating the regex but you didn't update the portion of code where it rebuilds the image name based on the matches, so you may just need to update that portion.

**Comment by inakiabt** [comment]
Great. I've merged my code and updated tests. Seems like everything's ok. Let me know, thanks.

**Comment by fillup** [comment]
Hi @inakiabt, I just tested your updates again but I still have failed tests. Here is the output:

```
1..32
ok 1 # skip (0) check that usage() returns string and exits with status code 20
ok 2 # skip (0) test assertRequiredArgumentsSet success
ok 3 # skip (0) test assertRequiredArgumentsSet status=5
ok 4 # skip (0) test assertRequiredArgumentsSet status=6
ok 5 # skip (0) test assertRequiredArgumentsSet status=7
ok 6 # skip (0) test assertRequiredArgumentsSet status=8
ok 7 # skip (0) test assertRequiredArgumentsSet status=9
ok 8 # skip (0) test parseImageName missing image name
ok 9 # skip (0) test parseImageName invalid image name 1
ok 10 # skip (0) test parseImageName invalid port
ok 11 # skip (0) test parseImageName root image no tag
ok 12 # skip (0) test parseImageName root image with tag
ok 13 # skip (0) test parseImageName repo image no tag
ok 14 # skip (0) test parseImageName repo image with tag
not ok 15 test parseImageName repo multilevel image no tag
# (in test file test.bats, line 117)
#   `[ "$output" == "repo/multi/level/image:latest" ]' failed
not ok 16 test parseImageName repo multilevel image with tag
# (in test file test.bats, line 125)
#   `[ "$output" == "repo/multi/level/image:v1.2.3" ]' failed
not ok 17 test parseImageName domain plus repo image no tag
# (in test file test.bats, line 133)
#   `[ "$output" == "docker.domain.com/repo/image:latest" ]' failed
not ok 18 test parseImageName domain plus repo image with tag
# (in test file test.bats, line 141)
#   `[ "$output" == "docker.domain.com/repo/image:1.2.3" ]' failed
not ok 19 test parseImageName domain plus repo multilevel image no tag
# (in test file test.bats, line 149)
#   `[ "$output" == "docker.domain.com/repo/multi/level/image:latest" ]' failed
not ok 20 test parseImageName domain plus repo multilevel image with tag
# (in test file test.bats, line 157)
#   `[ "$output" == "docker.domain.com/repo/multi/level/image:1.2.3" ]' failed
not ok 21 test parseImageName domain plus port plus repo image no tag
# (in test file test.bats, line 165)
#   `[ "$output" == "docker.domain.com:8080/repo/image:latest" ]' failed
not ok 22 test parseImageName domain plus port plus repo image with tag
# (in test file test.bats, line 173)
#   `[ "$output" == "docker.domain.com:8080/repo/image:1.2.3" ]' failed
not ok 23 test parseImageName domain plus port plus repo multilevel image no tag
# (in test file test.bats, line 181)
#   `[ "$output" == "docker.domain.com:8080/repo/multi/level/image:latest" ]' failed
not ok 24 test parseImageName domain plus port plus repo multilevel image with tag
# (in test file test.bats, line 189)
#   `[ "$output" == "docker.domain.com:8080/repo/multi/level/image:1.2.3" ]' failed
not ok 25 test parseImageName domain plus port plus repo image with tag from var
# (in test file test.bats, line 198)
#   `[ "$output" == "docker.domain.com:8080/repo/image:1487623908" ]' failed
not ok 26 test parseImageName domain plus port plus repo multilevel image with tag from var
# (in test file test.bats, line 207)
#   `[ "$output" == "docker.domain.com:8080/repo/multi/level/image:1487623908" ]' failed
not ok 27 test parseImageName using ecr style domain
# (in test file test.bats, line 215)
#   `[ "$output" == "121212345678.dkr.ecr.us-east-1.amazonaws.com/acct/repo:latest" ]' failed
not ok 28 test parseImageName using ecr style image name and tag from var
# (in test file test.bats, line 224)
#   `[ "$output" == "121212345678.dkr.ecr.us-east-1.amazonaws.com/acct/repo:1487623908" ]' failed
ok 29 # skip (0) test createNewTaskDefJson with single container in definition
ok 30 # skip (0) test createNewTaskDefJson with multiple containers in definition
ok 31 # skip (0) test parseImageName with tagonly option
ok 32 # skip (0) test createNewTaskDefJson with multiple containers in definition and replace only tags
```

If you run `docker-compose run --rm test` what is the output you get?

**Comment by inakiabt** [comment]
I've been testing locally using `bats` (no docker)! Now if I test using `docker-compose` I get the same errors you're getting.

Seems like the `bash` version on my computer (`GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)`) differs on how match strings using regular expressions than the one is installed on the alpine image.

I'm taking a look.

**Comment by inakiabt** [comment]
OK. After some issues merging develop into my branch, tests are passing OK (locally using `bats` and running them with `docker-compose`).
```bash
$ docker-compose run --rm test
fetch http://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/1) Installing bats (0.4.0-r2)
Executing busybox-1.25.1-r0.trigger
OK: 64 MiB in 31 packages
1..32
ok 1 # skip (0) check that usage() returns string and exits with status code 20
ok 2 # skip (0) test assertRequiredArgumentsSet success
ok 3 # skip (0) test assertRequiredArgumentsSet status=5
ok 4 # skip (0) test assertRequiredArgumentsSet status=6
ok 5 # skip (0) test assertRequiredArgumentsSet status=7
ok 6 # skip (0) test assertRequiredArgumentsSet status=8
ok 7 # skip (0) test assertRequiredArgumentsSet status=9
ok 8 # skip (0) test parseImageName missing image name
ok 9 # skip (0) test parseImageName invalid image name 1
ok 10 # skip (0) test parseImageName invalid port
ok 11 # skip (0) test parseImageName root image no tag
ok 12 # skip (0) test parseImageName root image with tag
ok 13 # skip (0) test parseImageName repo image no tag
ok 14 # skip (0) test parseImageName repo image with tag
ok 15 # skip (0) test parseImageName repo multilevel image no tag
ok 16 # skip (0) test parseImageName repo multilevel image with tag
ok 17 # skip (0) test parseImageName domain plus repo image no tag
ok 18 # skip (0) test parseImageName domain plus repo image with tag
ok 19 # skip (0) test parseImageName domain plus repo multilevel image no tag
ok 20 # skip (0) test parseImageName domain plus repo multilevel image with tag
ok 21 # skip (0) test parseImageName domain plus port plus repo image no tag
ok 22 # skip (0) test parseImageName domain plus port plus repo image with tag
ok 23 # skip (0) test parseImageName domain plus port plus repo multilevel image no tag
ok 24 # skip (0) test parseImageName domain plus port plus repo multilevel image with tag
ok 25 # skip (0) test parseImageName domain plus port plus repo image with tag from var
ok 26 # skip (0) test parseImageName domain plus port plus repo multilevel image with tag from var
ok 27 # skip (0) test parseImageName using ecr style domain
ok 28 # skip (0) test parseImageName using ecr style image name and tag from var
ok 29 # skip (0) test createNewTaskDefJson with single container in definition
ok 30 # skip (0) test createNewTaskDefJson with multiple containers in definition
ok 31 # skip (0) test parseImageName with tagonly option
ok 32 # skip (0) test createNewTaskDefJson with multiple containers in definition and replace only tags
```

Let me know, thanks.

**Comment by inakiabt** [comment]
I think it doesn't look good how I managed the code merge. I propose to redo it in a new branch and send a new pull request (my changes are minimal). I'll be happy to do it, just let me know.
Thanks.

**Comment by fillup** [comment]
Great, they are working for me now too and look good, I'll get this merged in.

**Pull request merged**
