### PR TITLE
Supported "--force-new-deployment" option

### PR DESCRIPTION
**Pull request by kakakakakku**
# Issue

- https://github.com/silinternational/ecs-deploy/issues/137

# What is this

In February, ECS supported new option `--force-new-deployment`.

We can use this option to deploy with no service definition changes ( = force ) .

- https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html

I supported `--force-new-deployment` for ecs-deploy.

screencapture-ap-northeast-1-console-aws-amazon-ecs-home-2018-04-17-22_27_56

# Log

It works with my ECS cluster 🎉 

```sh
$ ./ecs-deploy --cluster xxx --service-name yyy --force-new-deployment
Force a new deployment of the service
Waiting for service deployment to complete...
Service deployment successful.
```

# tests

```sh
$ docker-compose run --rm test
fetch http://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
(1/1) Installing bats (0.4.0-r2)
Executing busybox-1.25.1-r1.trigger
OK: 65 MiB in 31 packages
1..33
ok 1 # skip (0) check that usage() returns string and exits with status code 20
ok 2 # skip (0) test assertRequiredArgumentsSet success
ok 3 # skip (0) test assertRequiredArgumentsSet status=5
ok 4 # skip (0) test assertRequiredArgumentsSet status=6
ok 5 # skip (0) test assertRequiredArgumentsSet status=7
ok 6 # skip (0) test assertRequiredArgumentsSet status=8
ok 7 # skip (0) test assertRequiredArgumentsSet status=9
ok 8 # skip (0) test parseImageName missing image name
ok 9 # skip (0) test parseImageName invalid image name 1
ok 10 # skip (0) test parseImageName invalid port
ok 11 # skip (0) test parseImageName root image no tag
ok 12 # skip (0) test parseImageName root image with tag
ok 13 # skip (0) test parseImageName repo image no tag
ok 14 # skip (0) test parseImageName repo image with tag
ok 15 # skip (0) test parseImageName repo multilevel image no tag
ok 16 # skip (0) test parseImageName repo multilevel image with tag
ok 17 # skip (0) test parseImageName domain plus repo image no tag
ok 18 # skip (0) test parseImageName domain plus repo image with tag
ok 19 # skip (0) test parseImageName domain plus repo multilevel image no tag
ok 20 # skip (0) test parseImageName domain plus repo multilevel image with tag
ok 21 # skip (0) test parseImageName domain plus port plus repo image no tag
ok 22 # skip (0) test parseImageName domain plus port plus repo image with tag
ok 23 # skip (0) test parseImageName domain plus port plus repo multilevel image no tag
ok 24 # skip (0) test parseImageName domain plus port plus repo multilevel image with tag
ok 25 # skip (0) test parseImageName domain plus port plus repo image with tag from var
ok 26 # skip (0) test parseImageName domain plus port plus repo multilevel image with tag from var
ok 27 # skip (0) test parseImageName using ecr style domain
ok 28 # skip (0) test parseImageName using ecr style image name and tag from var
ok 29 # skip (0) test createNewTaskDefJson with single container in definition
ok 30 # skip (0) test createNewTaskDefJson with single container in definition for AWS Fargate
ok 31 # skip (0) test createNewTaskDefJson with multiple containers in definition
ok 32 # skip (0) test parseImageName with tagonly option
ok 33 # skip (0) test createNewTaskDefJson with multiple containers in definition and replace only tags
```

Thanks, please review 👍

### CODE REVIEW

**Comment by timoguin** [comment]
Would love to see this merged!

**Comment by alvarow** [comment]
This is great!

**Comment by kakakakakku** [comment]
I hope so 👍

**Comment by fillup** [comment]
Looks great, thanks!

**Pull request merged**
