### PR TITLE
At least one of memory or memoryReservation must be specified.

### PR DESCRIPTION
**Pull request by jsaivrr**

### CODE REVIEW

**Comment by forevermatt** [comment]
@jsaivrr Thanks for your input. Can you tell us a little bit more about what you were trying to do that didn't work?

**Comment by iorys** [comment]
"At least one of memory or memoryReservation must be specified". This is actually error message which I fixed with this PR changes.

**Comment by forevermatt** [comment]
I have added this to our backlog of issues to look into. Thank you.

**Review by briskt — APPROVED** [review]
looks good to me

**Comment by briskt** [comment]
Actually, I had to roll this back. In our workflow it produces the following error message:
> Invalid type for parameter memory, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

**Pull request merged**
